

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      show_sql: true
      format_sql: true

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbd:h2:mem:testdb;MODE=MySQL
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      show_sql: true
      format_sql: true

---
spring:
  config:
    activate:
      on-profile: prod

#  datasource:
#    url:
#    username:
#    password:

  jpa:
    hibernate:
      ddl-auto: none
