spring:
  config:
    activate:
      on-profile: dev

  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/yes_market?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      open-in-view: false
      properties:
        hibernate:
          format_sql = true

  redis:
    host: localhost
    port: 6379
